name: maid
description: A maid management app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animations: ^2.0.7
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
