// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuogPOeflTyx39gb8EgXW5JXTLt_IGww',
    appId: '1:246021485507:web:78c6d60dee03d72f5c4376',
    messagingSenderId: '246021485507',
    projectId: 'ad-maid-app',
    authDomain: 'ad-maid-app.firebaseapp.com',
    storageBucket: 'ad-maid-app.appspot.com',
    measurementId: 'G-7PZHN4D0C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevFqzAk1v7-BUBq_yb1xeujRYfW84bZ0',
    appId: '1:246021485507:android:cc83b9bc20d9b34c5c4376',
    messagingSenderId: '246021485507',
    projectId: 'ad-maid-app',
    storageBucket: 'ad-maid-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrtzgAXfQAtpE8N0IueupE9HqYpzaVBNc',
    appId: '1:246021485507:ios:3199d8cd644443e05c4376',
    messagingSenderId: '246021485507',
    projectId: 'ad-maid-app',
    storageBucket: 'ad-maid-app.appspot.com',
    iosClientId:
        '246021485507-trjukoj9pr7bdhuudfsvm8bdvvp9nc41.apps.googleusercontent.com',
    iosBundleId: 'dev.afridi1.maid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrtzgAXfQAtpE8N0IueupE9HqYpzaVBNc',
    appId: '1:246021485507:ios:3199d8cd644443e05c4376',
    messagingSenderId: '246021485507',
    projectId: 'ad-maid-app',
    storageBucket: 'ad-maid-app.appspot.com',
    iosClientId:
        '246021485507-trjukoj9pr7bdhuudfsvm8bdvvp9nc41.apps.googleusercontent.com',
    iosBundleId: 'dev.afridi1.maid',
  );
}
